spring:
  application:
    name: projectpilot-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: logs/projectpilot-server.log
